version: '3'
services:
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
